spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dispersion_db
    username: postgres
    password: ala1nna
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true  # Handles non-empty schema without history table

# External APIs (added missing properties)
external-apis:
  nws:
    base-url: https://api.weather.gov  # National Weather Service base URL
    user-agent: water-dispersion-app   # Custom user agent
  noaa:
    base-url: https://api.tidesandcurrents.noaa.gov/api/prod/datagetter  # NOAA tides base URL
    user-agent: water-dispersion-app                                      # Custom user agent

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.dispersion: DEBUG  # Your package

